version: '2.2'
services:
  simple-app-1:
    image: speedwing/prometheus-grafana:0.1
    ports:
      - "9000"
      - "9001:9000"
  simple-app-2:
    image: speedwing/prometheus-grafana:0.1
    ports:
      - "9000"
      - "9002:9000"
  prometheus:
    image: prom/prometheus:v2.7.1
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--storage.tsdb.path=/prometheus",
      "--storage.tsdb.retention=1d",
    ]
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus:/prometheus:rw
      - ./data/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:5.4.3
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana:rw
